AllCops:
  TargetRubyVersion: 3.0
  SuggestExtensions: false
  NewCops: enable

Metrics/CyclomaticComplexity:
  Enabled: true
  Max: 7

Metrics/BlockLength:
  Exclude:
    - '**/*'

Metrics/MethodLength:
  Enabled: true
  Max: 30

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
